"""Surface-language catalog for expanded fictional evidence scenarios."""

from __future__ import annotations


ROLE_CONCEPTS_V3 = {
    "Data": (
        ("SQL", "Excel", "Java"),
        ("Python data analysis", "R analysis", "content design"),
        ("Tableau", "Power BI", "backend APIs"),
        ("Power BI", "Tableau", "unit testing"),
        ("ETL pipelines", "data cleaning", "campaign planning"),
        ("A/B testing", "survey analysis", "Docker"),
        ("statistical modeling", "descriptive statistics", "CRM administration"),
        ("Pandas", "Excel formulas", "JavaScript"),
        ("data validation", "quality reporting", "product roadmaps"),
        ("analytics dashboards", "spreadsheet reports", "Kubernetes"),
        ("data modeling", "database reporting", "customer support"),
        ("forecasting", "historical reporting", "REST APIs"),
        ("dbt", "SQL transformations", "graphic design"),
        ("Airflow", "scheduled scripts", "sales operations"),
        ("data warehousing", "relational databases", "inventory planning"),
        ("data governance", "metadata documentation", "frontend styling"),
        ("experiment analysis", "KPI tracking", "network administration"),
        ("Looker", "Tableau", "container orchestration"),
        ("Snowflake", "PostgreSQL", "brand marketing"),
        ("data quality monitoring", "manual quality checks", "customer onboarding"),
    ),
    "ML": (
        ("PyTorch", "TensorFlow", "financial reporting"),
        ("TensorFlow", "PyTorch", "CRM administration"),
        ("scikit-learn", "statistical modeling", "frontend styling"),
        ("feature engineering", "data cleaning", "sales forecasting"),
        ("model deployment", "REST API development", "market research"),
        ("MLOps", "CI/CD", "customer onboarding"),
        ("natural language processing", "text analytics", "budget planning"),
        ("computer vision", "image processing", "stakeholder interviews"),
        ("model monitoring", "dashboard monitoring", "content writing"),
        ("experiment tracking", "project documentation", "account management"),
        ("ML data pipelines", "ETL pipelines", "roadmap planning"),
        ("ML experiment design", "A/B testing", "Java backend services"),
        ("XGBoost", "random forests", "visual design"),
        ("model serving", "backend API development", "customer surveys"),
        ("hyperparameter tuning", "model comparison", "financial reconciliation"),
        ("text embeddings", "TF-IDF retrieval", "CRM reporting"),
        ("time-series models", "business forecasting", "web styling"),
        ("data labeling workflows", "data cleaning", "vendor management"),
        ("drift detection", "data validation", "meeting facilitation"),
        ("GPU model training", "CPU batch processing", "market segmentation"),
    ),
    "Software": (
        ("Java", "Python", "financial modeling"),
        ("REST APIs", "GraphQL APIs", "customer segmentation"),
        ("Docker", "virtual machines", "market research"),
        ("Git", "document versioning", "forecasting"),
        ("relational databases", "spreadsheet storage", "content strategy"),
        ("unit testing", "manual testing", "sales operations"),
        ("CI/CD", "release checklists", "stakeholder interviews"),
        ("JavaScript", "HTML and CSS", "statistical modeling"),
        ("backend services", "internal automation", "brand marketing"),
        ("cloud deployment", "on-premise deployment", "CRM reporting"),
        ("system design", "process mapping", "survey research"),
        ("Kubernetes", "Docker Compose", "financial reconciliation"),
        ("TypeScript", "JavaScript", "budget planning"),
        ("PostgreSQL", "SQLite", "customer support tooling"),
        ("message queues", "scheduled jobs", "market analysis"),
        ("microservices", "modular applications", "spreadsheet reporting"),
        ("observability", "application logging", "product interviews"),
        ("authentication systems", "session management", "campaign tracking"),
        ("infrastructure as code", "deployment scripts", "financial forecasting"),
        ("performance profiling", "load testing", "content operations"),
    ),
    "Business": (
        ("Intercom", "Zendesk", "PyTorch"),
        ("Salesforce", "HubSpot", "computer vision"),
        ("stakeholder interviews", "customer surveys", "Docker"),
        ("process mapping", "workflow documentation", "TensorFlow"),
        ("KPI reporting", "operational reporting", "Java services"),
        ("financial modeling", "budget reporting", "frontend development"),
        ("market research", "customer interviews", "Kubernetes"),
        ("CRM administration", "customer support tools", "ETL pipelines"),
        ("requirements gathering", "meeting facilitation", "model deployment"),
        ("product roadmaps", "project planning", "SQL optimization"),
        ("Excel forecasting", "spreadsheet reporting", "REST APIs"),
        ("customer segmentation", "audience research", "unit testing"),
        ("competitive analysis", "market scanning", "container deployment"),
        ("business cases", "cost summaries", "backend services"),
        ("change management", "training coordination", "feature engineering"),
        ("process improvement", "operational reviews", "database tuning"),
        ("vendor evaluation", "procurement research", "model monitoring"),
        ("OKR planning", "KPI tracking", "API testing"),
        ("workshop facilitation", "structured interviews", "cloud deployment"),
        ("risk analysis", "issue tracking", "natural language processing"),
    ),
}

ROLE_TITLES_V3 = {
    "Data": "Data and Analytics",
    "ML": "Machine Learning",
    "Software": "Software Engineering",
    "Business": "Business and Product Operations",
}

REQUIREMENT_TEMPLATES_V3 = (
    "Hands-on {skill} experience will be important in this position.",
    "The person in this role will regularly work with {skill}.",
    "Prior delivery work involving {skill} is part of the core qualification.",
    "Applicants should be comfortable applying {skill} without close supervision.",
    "Day-to-day responsibilities include practical use of {skill}.",
    "The team is looking for demonstrated experience in {skill}.",
    "A successful candidate can point to completed work involving {skill}.",
    "This role owns deliverables that depend on {skill}.",
    "Experience taking {skill} from planning through delivery is expected.",
    "Core requirement: practical capability with {skill}.",
    "The work calls for someone who has applied {skill} in a project setting.",
    "Candidates are expected to make independent use of {skill}.",
    "Comfort working directly with {skill} is essential.",
    "The position involves building or improving workflows with {skill}.",
    "Evidence of applied {skill} experience is required.",
    "The incoming team member should have delivered outcomes using {skill}.",
    "A key responsibility is executing project work through {skill}.",
    "We need someone able to use {skill} on real delivery tasks.",
    "Practical exposure to {skill}, beyond conceptual knowledge, is expected.",
    "This opening requires a track record of using {skill} to complete work.",
)

COMPOUND_REQUIREMENT_TEMPLATES = (
    "The role centers on {primary} and requires connecting that work with {adjacent}.",
    "Candidates must deliver {primary} workflows that integrate with {adjacent}.",
    "This position combines hands-on {primary} work with practical {adjacent} use.",
    "Successful delivery requires both {primary} and {adjacent} in one workflow.",
    "The team needs evidence covering {primary} as well as {adjacent}.",
    "Day-to-day ownership spans {primary} delivery and {adjacent} integration.",
)

SURFACE_STYLES = (
    "{clause}.",
    "During a six-week delivery cycle, {clause_lower}.",
    "{clause}; the work was documented in the final handoff.",
    "Project contribution — {clause_lower}.",
    "Within a cross-functional assignment, {clause_lower}.",
    "{clause}, with the approach reviewed during the project retrospective.",
    "The project record notes that the candidate {clause_no_subject}.",
    "In the implementation phase, {clause_lower}.",
    "{clause}. This formed one part of a broader operational initiative.",
    "Selected experience: {clause_lower}.",
    "For an internal delivery milestone, {clause_lower}.",
    "{clause}; teammates reviewed the resulting work products.",
    "As part of a time-bound project, {clause_lower}.",
    "Responsibility included the following: {clause_lower}.",
    "{clause}. The result was included in the team handover.",
    "One documented contribution was that the candidate {clause_no_subject}.",
)

HANDS_ON_CORES = (
    "Used {skill} to complete a multi-step delivery workflow",
    "Built a working project component with {skill}",
    "Applied {skill} while resolving a defined operational problem",
    "Owned implementation of a workflow based on {skill}",
    "Configured and used {skill} for a documented project outcome",
    "Delivered a project milestone that relied on {skill}",
    "Improved an existing process through hands-on use of {skill}",
    "Created and checked a practical solution using {skill}",
    "Worked directly in {skill} to produce a reviewed deliverable",
    "Implemented the project approach with {skill} as a core method",
    "Used {skill} across planning, execution, and validation",
    "Completed an end-to-end assignment centered on {skill}",
)

LIMITED_CORES = (
    "Modified a small part of an existing {skill} workflow without owning its design",
    "Used {skill} for one bounded task while a teammate handled the main implementation",
    "Completed a guided {skill} prototype but did not deploy or maintain it",
    "Assisted with {skill} checks after the core workflow had already been built",
    "Adapted a provided {skill} example for a short internal exercise",
    "Contributed one {skill} step to a larger process owned by another team member",
)

MENTION_CORES = (
    "Reviewed documentation for {skill} but did not apply it to project work",
    "Observed a demonstration of {skill} without operating it independently",
    "Added {skill} to a future learning plan and had not started practical work",
    "Compared tools that included {skill} but did not implement any option",
    "Attended a project discussion about {skill} without contributing to that workstream",
    "Shadowed a colleague using {skill} and did not complete a hands-on task",
)

GENERIC_STRONG_CORES = (
    "Led weekly coordination and converted open issues into an action log",
    "Prepared a reviewed handover covering timelines, owners, and delivery risks",
    "Reworked an operating checklist and reduced missing follow-up items",
    "Consolidated stakeholder feedback into a prioritized delivery plan",
    "Maintained a quality log and presented recurring issues to the project team",
    "Built a structured reporting pack for an unrelated operational workstream",
)
