"""Reviewable vocabulary used by deterministic evidence constraint features."""

from __future__ import annotations

import re


TECHNOLOGY_TERMS = {
    "airflow",
    "amplitude",
    "android",
    "angular",
    "ansible",
    "appsflyer",
    "ats",
    "aws",
    "azure",
    "bigquery",
    "c#",
    "c++",
    "django",
    "docker",
    "excel",
    "fastapi",
    "firebase",
    "flask",
    "gcp",
    "git",
    "github",
    "gitlab",
    "hadoop",
    "ios",
    "java",
    "javascript",
    "jira",
    "json",
    "jupyter",
    "keras",
    "kotlin",
    "kubernetes",
    "linux",
    "looker",
    "looker studio",
    "matlab",
    "mongodb",
    "mysql",
    "node.js",
    "numpy",
    "objective-c",
    "oracle",
    "pandas",
    "postgresql",
    "power bi",
    "python",
    "pytorch",
    "react",
    "reactjs",
    "redis",
    "ruby",
    "salesforce",
    "scala",
    "scikit-learn",
    "seaborn",
    "snowflake",
    "spark",
    "spring",
    "spring boot",
    "sql",
    "swift",
    "swiftui",
    "tableau",
    "tensorflow",
    "terraform",
    "typescript",
    "xgboost",
    "xml",
    "xsd",
    "yaml",
}
TERM_FAMILY_ALIASES = {
    "machine_learning": (
        "machine learning",
        "deep learning",
        "computer vision",
        "image processing",
        " ml ",
        " dl ",
        " ai ",
        "tensorflow",
        "pytorch",
        "keras",
        "scikit-learn",
        "xgboost",
        "predictive model",
        "prediction algorithm",
        "semantic search",
    ),
    "programming_language": (
        "python",
        "java",
        "javascript",
        "typescript",
        "scala",
        "kotlin",
        "ruby",
        "c++",
        "c#",
        "objective-c",
        "swift",
    ),
    "java_backend": ("spring", "spring boot", "spring data", "j2ee", "jee"),
    "data_engineering": (
        "data pipeline",
        "data lake",
        "etl",
        "airflow",
        "spark",
        "hadoop",
        "bigquery",
    ),
    "database": (
        "database",
        "sql",
        "mongodb",
        "postgresql",
        "mysql",
        "oracle",
        "snowflake",
    ),
    "reporting": (
        "amplitude",
        "appsflyer",
        "firebase",
        "looker",
        "looker studio",
        "reporting",
        "dashboard",
        "tableau",
        "power bi",
        "business objects",
        "visualization",
        "visualisation",
    ),
    "mobile": (
        "mobile development",
        "android",
        "ios",
        "objective-c",
        "swift",
        "swiftui",
    ),
    "recruiting_platform": (
        " ats ",
        "applicant tracking",
        "candidate tracking",
        "recruiting workflow",
    ),
    "data_format": ("xml", "xsd", "json", "yaml", "3nf"),
    "cloud": ("aws", "azure", "gcp", "cloud platform"),
    "devops": (
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "continuous integration",
        "ci/cd",
    ),
    "frontend": ("react", "reactjs", "angular", "frontend", "front-end"),
}
DEGREE_LEVELS = {
    "bachelor": 1,
    "bachelors": 1,
    "bachelor's": 1,
    "undergraduate": 1,
    "master": 2,
    "masters": 2,
    "master's": 2,
    "mba": 2,
    "phd": 3,
    "ph.d": 3,
    "doctorate": 3,
    "doctoral": 3,
}
ELIGIBILITY_PATTERNS = {
    "work_authorization": re.compile(
        r"\b(?:work authori[sz]ation|authori[sz]ed to work|right to work)\b",
        re.IGNORECASE,
    ),
    "security_clearance": re.compile(
        r"\b(?:security clearance|clearance|secret cleared|top secret)\b",
        re.IGNORECASE,
    ),
    "citizenship": re.compile(
        r"\b(?:citizen|citizenship|permanent resident|permanent residency)\b",
        re.IGNORECASE,
    ),
}
WEAK_ASSERTION_PATTERN = re.compile(
    r"\b(?:familiar with|exposure to|observed|shadowed|tutorial|coursework|"
    r"learning|studied|assisted with|helped with|prepared to)\b",
    re.IGNORECASE,
)
NEGATED_DELIVERY_PATTERN = re.compile(
    r"\b(?:did not|didn't|never|without)\b.{0,45}\b"
    r"(?:build|built|deploy|deployed|implement|implemented|manage|managed|"
    r"use|used|deliver|delivered|develop|developed)\b",
    re.IGNORECASE,
)
CLAUSE_SPLIT_PATTERN = re.compile(
    r"\s*(?:;|,(?=\s)|\band\b|\bplus\b)\s*",
    re.IGNORECASE,
)
ACRONYM_PATTERN = re.compile(r"\b[A-Z][A-Z0-9+#.-]{1,7}\b")
